packages:
  home-assistant-voice: !include home-assistant-voice.factory.yaml

esphome:
  name: ha-voice-8mb
  project:
    name: MarekCounts.Home Assistant Voice PE Streaming
    version: 2026.7.4-streaming.3

esp32:
  flash_size: 8MB

dashboard_import:
  package_import_url: github://MarekCounts/home-assistant-voice-pe/home-assistant-voice.8mb.yaml@dev
